export type IGenreFiction =
  | 'Action and adventure'
  | 'Alternate history'
  | 'Anthology'
  | 'Chick lit'
  | "Children's"
  | 'Classic'
  | 'Comic book'
  | 'Coming-of-age'
  | 'Crime'
  | 'Drama'
  | 'Fairytale'
  | 'Fantasy'
  | 'Graphic novel'
  | 'Historical fiction'
  | 'Horror'
  | 'Mystery'
  | 'Paranormal romance'
  | 'Picture book'
  | 'Poetry'
  | 'Political thriller'
  | 'Romance'
  | 'Satire'
  | 'Science fiction'
  | 'Short story'
  | 'Suspense'
  | 'Thriller'
  | 'Western'
  | 'Young adult';

export type IGenreNonFiction =
  | 'Art/architecture'
  | 'Autobiography'
  | 'Biography'
  | 'Business/economics'
  | 'Crafts/hobbies'
  | 'Cookbook'
  | 'Diary'
  | 'Dictionary'
  | 'Encyclopedia'
  | 'Food'
  | 'Guide'
  | 'Health/fitness'
  | 'History'
  | 'Home and garden'
  | 'Humor'
  | 'Journal'
  | 'Math'
  | 'Memoir'
  | 'Philosophy'
  | 'Politics'
  | 'Prayer'
  | 'Religion'
  | 'Textbook'
  | 'True crime'
  | 'Review'
  | 'Science'
  | 'Self help'
  | 'Sports and leisure'
  | 'Travel'
  | 'True crime';
