#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn install ||
    (
        echo '❌ Failed to do yarn.'
        echo 'Please try using "yarn install" command again.'
        false
    )

echo 'Dependcies installed.'